[project]
name = "linux-egg-timer"
version = "1.0.0"
description = "An Applet that allows for running multiple custom timers."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argparse==1.4.0",
    "customtkinter==6.0.0",
    "packaging==26.2",
    "pillow==12.3.0",
]

[tool.pdm]  # https://pdm-project.org/latest/reference/configuration/
distribution = false  # prevent pdm from 'installing' modules in 'src' and updating while adding/removing.
python.use_venv = false

[tool.ty.environment]
extra-paths = ["./__pypackages__/3.14/lib"]  # so the ruff linter picks up modules installed via container
