[project]
name = "linux-egg-timer"
version = "1.0.0"
description = "An Applet that allows for running multiple custom timers."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argparse==1.4.0",
    "customtkinter==6.0.0",
    "packaging==26.2",
    # "timedelta==2020.12.3",
    # "ttkthemes==3.3.0",
]

[tool.ty.environment]
extra-paths = ["./python_modules"]  # so the ruff linter picks up modules installed via container

[tool.uv]
link-mode = "copy"
